export { default as Activities } from "./activities";
export { default as Home } from "./home";
export { default as Register } from "./register";
export { default as Routines } from "./routines";
export { default as Login } from "./login";
export { default as MyRoutines } from "./myRoutines";
export { default as App } from "./app";
export { default as Header } from "./header";
export { default as Logout } from "./logout";