export { default as Activities } from "./Activities";
export { default as Home } from "./Home";
export { default as Register } from "./Register";
export { default as Routines } from "./Routines";
export { default as Login } from "./Login";
export { default as MyRoutines } from "./MyRoutines";
export { default as App } from "./App";
export { default as Header } from "./Header";
export { default as Logout } from "./Logout";
export { default as AddActivity} from "./AddActivity";
export {default as AddRoutine} from "./AddRoutine";
export {default as EditRoutine} from "./EditRoutine";